name: Build Spigot 1.8.8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Download BuildTools
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      # 这里的版本号必须改为 1.8.8
      - name: Build Spigot 1.8.8
        run: java -jar BuildTools.jar --rev 1.8.8

      - name: Upload Spigot Jar
        uses: actions/upload-artifact@v4
        with:
          name: Spigot-1.8.8-Core
          # 产出的文件名也会变成 1.8.8
          path: spigot-1.8.8-R0.1-SNAPSHOT.jar
